// Code generated by go generate; DO NOT EDIT.
//
// file generated at: 2020-01-28 20:23:03.8083682 +0000 UTC m=+1.003523701
// using data from:   https://raw.github.com/afiune/godist/master/glob_dist.json
// and generator:     https://github.com/chef/go-libs/distgen
//

package config

var (
	AutomateProduct = "Chef Automate"
	ClientExec      = "chef-client"
	ClientProduct   = "Chef Infra Client"
	MainWebsite     = "https://chef.io"
	ServerProduct   = "Chef Infra Server"
	ShellExec       = "chef-shell"
	SoloExec        = "chef-solo"
	SoloProduct     = "Chef Infra Solo"
	ZeroExec        = "chef-zero"
)
